name: build

on:
    push:
        branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: checkout
            uses: actions/checkout@v2
    
          - name: Setup Go
            uses: actions/setup-go@v2
            with:
              go-version: '1.13.0'
        
          - name: Build
            run:  make -j $(nproc)

